### ISSUE TITLE
Dashboard fails to load CDB lists due to ERR_BAD_REQUEST 

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh-dashboard#192]
## Description

A [community](https://github.com/wazuh/community/issues/26270) user has reported that they followed the configuration described in [this post](https://wazuh.com/blog/building-ioc-files-for-threat-intelligence-with-wazuh-xdr/), which creates a CDB list with malicious URLs. The issue they are facing is that when attempting to access the CDB lists from the dashboard, they receive the following error:

```
Wazuh API error: ERR_BAD_REQUEST - Bad format in CDB list /var/ossec/etc/lists/mal-url-list
RequestError: Wazuh API error: ERR_BAD_REQUEST - Bad format in CDB list /var/ossec/etc/lists/mal-url-list
    at settle (https://192.168.68.59/47402/bundles/plugin/wazuh/wazuh.plugin.js:8:20234)
    at XMLHttpRequest.onloadend (https://192.168.68.59/47402/bundles/plugin/wazuh/wazuh.plugin.js:8:25708)
```

This error causes the view to "break," and none of the other lists are displayed.

Additionally, I have observed that the manager interprets and constructs the list correctly:

```
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/audit-keys'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/amazon/aws-eventnames'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/security-eventchannel'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/mal-url-list'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:666 at main(): DEBUG: Building CDB lists.
```

Since the manager does not report any error in the list's content, it would be advisable to investigate if there is an issue loading the mal-url-list from the dashboard. The list is a plain text file, so why does the error message refer to XML?

I am attaching the list for you to analyze and conduct any necessary tests.

[mal-url-list.zip](https://github.com/user-attachments/files/15764578/mal-url-list.zip)

**Comment by guidomodarelli** [comment]
Update 2024/09/20

- `/plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&view=menu&parent=\"%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),md5(999999999)),NULL,NULL,NULL,NULL,NULL--%20aa:`

**Comment by JuanGarriuz** [comment]
- Double `//`
`//wp-login.php:`

- ???
`/?cffaction=get_data_from_database&query=SELECT%20*%20from%20wp_users:`
